# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week 6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week 6

end
